entity filtering feature for reactive option
jhipster/jhipster-bom pull request #1003
Opened 2022-10-03 22:10 UTC by dwarakaprasad

ConditionBuilder class to build conditions from EntityCriteria

fix #14616

2022-10-04 21:01 UTC, gzsombor commented
Great patch, I see just a couple of minor things

2022-10-04 21:01 UTC, gzsombor requested changes

2022-10-06 02:54 UTC, dwarakaprasad commented on jhipster-framework/src/main/java/tech/jhipster/service/ConditionBuilder.java
> +    }
Done

2022-10-06 02:54 UTC, dwarakaprasad commented on jhipster-framework/src/main/java/tech/jhipster/service/ConditionBuilder.java
> +            allFilters.add(Conditions.just("" + column + " IS NOT NULL"));
Done

2022-10-06 02:54 UTC, dwarakaprasad commented on jhipster-framework/src/test/java/tech/jhipster/service/demo/ConditionBuilderTest.java
> +		assert (builder.buildConditions().toString())
Done

2022-10-06 03:17 UTC, dwarakaprasad commented on jhipster-framework/src/main/java/tech/jhipster/service/ConditionBuilder.java
> +    private <X extends Comparable<? super X>> void buildRangeConditions(RangeFilter<X> rangeData, Column column, Class<?> targetClass) {
Done

2022-10-11 17:38 UTC, DanielFran commented
@gzsombor Your requested changes have been impleted. Can you confirm we can merge the PR?
Thanks

2022-10-11 21:55 UTC, gzsombor commented
Sorry, I haven't had time, but I still see, that on the values, toString is called which makes me worried. I don't know by heart, how the R2DBC drivers, and the database are handling types, but I would be generally surprised that all - with all possible locale settings ordering/filtering would work correctly, when strings are passed, instead of the original types. Is there any reason, why you insist on using strings?

2022-10-13 03:05 UTC, dwarakaprasad commented
Thank you for your review comment @gzsombor.
I actually did start with using the original type but the Instant, LocalDate & ZonedDateTime were not getting decoded in the query and hence was causing syntax error (this was with postgress). All the field types were causing issues with H2 (syntax error) and hence had to settle with string for everything.

This code is tested with all the supported db's in the integration tests see jhipster/generator-jhipster#19959

2022-10-28 10:45 UTC, DanielFran commented
@gzsombor Is it OK to merge it or should we investigate more the toString?

2022-11-01 12:41 UTC, DanielFran approved these changes

2022-11-01 12:41 UTC, merged