refactor & sonar fixes
jhipster/jhipster-bom pull request #1472
Opened 2023-11-20 22:29 UTC by DishaAnand

`Description:`
- refactored few files
- fixed sonar issues

`Sonar Issue Id:`
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AYMy8ftoR6xvCwI5pG55
- https://sonarcloud.io/project/issues?fileUuids=AXWEj8X7uEAlCkyrserW&resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AXDLQPyj7NPLvZRIY3yr
- https://sonarcloud.io/project/issues?fileUuids=AXWEj8X6uEAlCkyrserI&resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AW8i7R24FN2GgBTo8gHa
- https://sonarcloud.io/project/issues?fileUuids=AYQzN3Lt2_PoappU_KSf&resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AYQzN3fW2_PoappU_KSh
- https://sonarcloud.io/project/issues?fileUuids=AYQzN3Lt2_PoappU_KSf&resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AYQzN3fW2_PoappU_KSj
- https://sonarcloud.io/project/issues?fileUuids=AYQzN3Lt2_PoappU_KSf&resolved=false&types=CODE_SMELL&id=jhipster-framework&open=AYQzN3fW2_PoappU_KSk

`Refactored Files:`
- jhipster-framework/src/main/java/tech/jhipster/config/cache/PrefixedKeyGenerator.java
- jhipster-framework/src/main/java/tech/jhipster/config/liquibase/AsyncSpringLiquibase.java
- jhipster-framework/src/main/java/tech/jhipster/config/locale/AngularCookieLocaleResolver.java
- jhipster-framework/src/main/java/tech/jhipster/web/util/HeaderUtil.java
- jhipster-framework/src/main/java/tech/jhipster/web/util/LinkHeaderUtil.java
- jhipster-framework/src/main/java/tech/jhipster/web/util/PaginationUtil.java

`Lint File:`
- jhipster-framework/src/test/java/tech/jhipster/config/locale/AngularCookieLocaleResolverTest.java

`Test File:`
- jhipster-framework/src/test/java/tech/jhipster/web/filter/reactive/CachingHttpHeadersFilterTest.java
- jhipster-framework/src/test/java/tech/jhipster/web/util/HeaderUtilTest.java

2023-11-20 22:57 UTC, DishaAnand commented
Hi @DanielFran 
I have made some refactoring changes to the awesome repository
but few checks are failing

can you kindly guide?

2023-11-21 18:03 UTC, DanielFran commented
@DishaAnand closed/reopen to see if cache issue is resolved

2023-11-21 18:15 UTC, DanielFran requested changes

2023-11-21 18:15 UTC, DanielFran commented on jhipster-framework/src/main/java/tech/jhipster/web/util/HeaderUtil.java
> +    public static HttpHeaders createAlertHeader(String applicationName, String alertMessage, String alertParam) {
@DishaAnand You rename this method that is used in generator-jhipster, so pipelines fail

2023-11-22 00:06 UTC, DishaAnand commented
Hi @DanielFran 
Thank you so much for taking your time 
and reviewing & letting me know where the issue was.

I have pushed the changes
Kindly review!

Thank you ! : )

2023-11-22 18:10 UTC, DanielFran requested changes

2023-11-22 18:10 UTC, DanielFran commented on jhipster-framework/src/main/java/tech/jhipster/async/ExceptionHandlingAsyncTaskExecutor.java
> +    @Deprecated(since = "version", forRemoval = true)
```suggestion
    @Deprecated(since = "7.8.0", forRemoval = true)
```

2023-11-22 18:10 UTC, DanielFran commented on jhipster-framework/src/main/java/tech/jhipster/config/liquibase/AsyncSpringLiquibase.java
> +    public static final String EXCEPTION_MESSAGE = "Liquibase could not start correctly, your database is NOT ready: " + "{}";
```suggestion
    public static final String EXCEPTION_MESSAGE = "Liquibase could not start correctly, your database is NOT ready: {}";
```

2023-11-22 18:20 UTC, DishaAnand commented on jhipster-framework/src/main/java/tech/jhipster/async/ExceptionHandlingAsyncTaskExecutor.java
> +    @Deprecated(since = "version", forRemoval = true)
added this version number

2023-11-22 18:20 UTC, DishaAnand commented on jhipster-framework/src/main/java/tech/jhipster/config/liquibase/AsyncSpringLiquibase.java
> +    public static final String EXCEPTION_MESSAGE = "Liquibase could not start correctly, your database is NOT ready: " + "{}";
removed the unwanted character

2023-11-22 18:51 UTC, DishaAnand commented
Hi @DanielFran
Thank you so much for reviewing the changes

I have made the suggested changes.

KIndly have a look!
Thank you 😊

2023-11-22 18:53 UTC, DanielFran approved these changes

2023-11-22 18:53 UTC, merged

2023-11-22 18:53 UTC, DanielFran commented
Thanks @DishaAnand for the contribution