fix #17187
jhipster/jhipster-bom pull request #552
Opened 2021-11-30 17:33 UTC by Tcharl

2021-11-30 18:27 UTC, pascalgrimaud commented
The commit msg is not nice, as we can't know what you're doing without looking the diff :-)

2021-11-30 21:58 UTC, DanielFran commented
Updated title

2021-12-01 05:54 UTC, pascalgrimaud commented
There is already a snapshot artifact with GitHub for main branch, if I'm correct, but I don't use it.

About the CI, you could do something similar to https://github.com/jhipster/generator-jhipster/pull/17068/files but don't forget to revert before the merge

That's why, in my opinion, splitting code into lib is a bad idea for contributors. As a core team member, it was not simple for you, I can't imagine for a new contributor.
Anyway, it's another subject.

2021-12-01 09:58 UTC, Tcharl commented
May be just a matter of explaining more things in the CONTRIBUTING.md.
Honestly, I've spent hours to figure out how configure IJ to test generator-jhipster

2021-12-07 09:57 UTC, DanielFran requested changes

2021-12-07 09:57 UTC, DanielFran commented on jhipster-dependencies/pom.xml
> +            </dependency>
```suggestion
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>${testng.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- Spring Cloud Netflix dependencies are no longer managed by Spring Cloud's BOM -->
            <!-- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes -->
```

2021-12-21 21:22 UTC, merged