Upgrade to Spring Boot 3.0 M4
jhipster/jhipster-bom pull request #986
Opened 2022-09-21 02:17 UTC by mraible

2022-09-24 14:08 UTC, mraible commented
@DanielFran Do you know how to fix the JDK issue? I can't seem to figure out where to set Java 17.

```
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce-versions) @ jhipster-parent ---
Error:  Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
You are running an older version of Java. JHipster requires at least JDK 17
```

2022-09-25 14:35 UTC, DanielFran commented
> @DanielFran Do you know how to fix the JDK issue? I can't seem to figure out where to set Java 17.
> 
> ```
> [INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce-versions) @ jhipster-parent ---
> Error:  Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
> You are running an older version of Java. JHipster requires at least JDK 17
> ```

@mraible This happens compiling the bom only, or the generator?

2022-09-25 15:13 UTC, mraible commented
@DanielFran Marcelo fixed the compilation issue.

2022-10-04 19:54 UTC, mraible commented
I was unable to find an `OpenApiCustomer` class after upgrading to SpringDoc 2.0.0-M6. Maybe it's not needed anymore?

2022-10-05 16:34 UTC, DanielFran commented on jhipster-framework/src/main/java/tech/jhipster/config/apidoc/JHipsterSpringDocGroupsConfiguration.java
> +        List<OpenApiCustomizer> openApiCustomisers,
```suggestion
        List<OpenApiCustomizer> openApiCustomizers,
```

2022-10-05 16:35 UTC, DanielFran commented on jhipster-framework/src/main/java/tech/jhipster/config/apidoc/JHipsterSpringDocGroupsConfiguration.java
> +        List<OpenApiCustomizer> openApiCustomisers,
Rename variable

2022-10-05 16:36 UTC, DanielFran requested changes
Rename variable

2022-10-14 23:11 UTC, mshima commented
Can we change the version to don't conflict with current main?

2022-10-15 15:48 UTC, mraible commented
Yes, feel free to change the version.

2022-10-16 18:57 UTC, mshima commented
8.0.0-SNAPSHOT?

2022-10-16 20:31 UTC, mraible commented
Works for me.

2022-11-13 23:48 UTC, mraible commented
I'm able to reproduce the failing e2e test that happens with the ng-default job. It seems that when you edit the field, there's two required fields that need to be selected before the save button is enabled.

```
[1]   TestTwoRelationshipsSameEntity e2e test
[1]     ✓ TestTwoRelationshipsSameEntities menu should load TestTwoRelationshipsSameEntities page (1230ms)
[1]     TestTwoRelationshipsSameEntity page
[1]       create button click
[1]         ✓ should load create TestTwoRelationshipsSameEntity page (649ms)
[1]       with existing value
[1]         ✓ detail button click should load details TestTwoRelationshipsSameEntity page (636ms)
[1]         ✓ edit button click should load edit TestTwoRelationshipsSameEntity page and go back (608ms)
[1]         (Attempt 1 of 3) edit button click should load edit TestTwoRelationshipsSameEntity page and save
[1]         (Attempt 2 of 3) edit button click should load edit TestTwoRelationshipsSameEntity page and save
[1]         1) edit button click should load edit TestTwoRelationshipsSameEntity page and save
[1]         ✓ last delete button click should delete instance of TestTwoRelationshipsSameEntity (676ms)
[1]     new TestTwoRelationshipsSameEntity page
[1] Cannot find coverage file /home/runner/work/generator-jhipster/generator-jhipster/app/.nyc_output/out.json
[1] Skipping coverage report
[1]       ✓ should create an instance of TestTwoRelationshipsSameEntity (837ms)
[1] 
[1] 
[1]   6 passing (21s)
[1]   1 failing
[1] 
[1]   1) TestTwoRelationshipsSameEntity e2e test
[1]        TestTwoRelationshipsSameEntity page
[1]          with existing value
[1]            edit button click should load edit TestTwoRelationshipsSameEntity page and save:
[1]      CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is `disabled`:
[1] 
[1] `<button type="submit" id="save-entity" data-cy="entityCreateSaveButton" class="btn btn-primary" disabled="">...</button>`
```

2022-12-02 20:30 UTC, mraible commented on jhipster-dependencies/pom.xml
> +        <spring-cloud.version>2022.0.0-RC2</spring-cloud.version>
```suggestion
        <spring-cloud.version>2022.0.0-RC3</spring-cloud.version>
```
https://spring.io/blog/2022/12/02/spring-cloud-2022-0-0-release-candidate-3-codename-kilburn-has-been-released

2022-12-09 20:48 UTC, merged